import com.google.gson.Gson;
import com.molean.isletopia.distribute.individual.ServerInfoUpdater;
import org.ietf.jgss.GSSContext;

import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

public class StatisticTest {
    public static void main(String[] args) throws IOException {
        String str1 = "minecraft:lime_stained_glass\n" +
                "minecraft:green_banner\n" +
                "minecraft:red_stained_glass_pane\n" +
                "minecraft:black_dye\n" +
                "minecraft:crimson_fungus\n" +
                "minecraft:yellow_wool\n" +
                "minecraft:oak_sign\n" +
                "minecraft:red_sand\n" +
                "minecraft:blaze_powder\n" +
                "minecraft:chain\n" +
                "minecraft:blue_stained_glass_pane\n" +
                "minecraft:diamond_shovel\n" +
                "minecraft:nether_brick\n" +
                "minecraft:gray_wool\n" +
                "minecraft:granite\n" +
                "minecraft:diamond_helmet\n" +
                "minecraft:magenta_concrete_powder\n" +
                "minecraft:light_blue_concrete_powder\n" +
                "minecraft:stone_pressure_plate\n" +
                "minecraft:iron_door\n" +
                "minecraft:gray_stained_glass_pane\n" +
                "minecraft:black_wool\n" +
                "minecraft:gray_stained_glass\n" +
                "minecraft:bubble_coral_block\n" +
                "minecraft:name_tag\n" +
                "minecraft:lime_concrete_powder\n" +
                "minecraft:pink_stained_glass\n" +
                "minecraft:warped_stairs\n" +
                "minecraft:turtle_helmet\n" +
                "minecraft:blue_stained_glass\n" +
                "minecraft:redstone_lamp\n" +
                "minecraft:end_rod\n" +
                "minecraft:soul_campfire\n" +
                "minecraft:chest_minecart\n" +
                "minecraft:smithing_table\n" +
                "minecraft:mossy_cobblestone\n" +
                "minecraft:nether_brick_fence\n" +
                "minecraft:sticky_piston\n" +
                "minecraft:red_nether_bricks\n" +
                "minecraft:fletching_table\n" +
                "minecraft:coal_ore\n" +
                "minecraft:green_stained_glass\n" +
                "minecraft:painting\n" +
                "minecraft:stone_brick_stairs\n" +
                "minecraft:lectern\n" +
                "minecraft:wooden_hoe\n" +
                "minecraft:golden_leggings\n" +
                "minecraft:stone_slab\n" +
                "minecraft:iron_pickaxe\n" +
                "minecraft:sandstone\n" +
                "minecraft:netherite_ingot\n" +
                "minecraft:composter\n" +
                "minecraft:polished_blackstone_bricks\n" +
                "minecraft:tube_coral_block\n" +
                "minecraft:dark_prismarine\n" +
                "minecraft:cyan_wool\n" +
                "minecraft:nautilus_shell\n" +
                "minecraft:warped_fungus\n" +
                "minecraft:golden_carrot\n" +
                "minecraft:cocoa_beans\n" +
                "minecraft:magenta_wool\n" +
                "minecraft:redstone_ore\n" +
                "minecraft:jukebox\n" +
                "minecraft:orange_shulker_box\n" +
                "minecraft:iron_nugget\n" +
                "minecraft:diamond_hoe\n" +
                "minecraft:soul_torch\n" +
                "minecraft:red_banner\n" +
                "minecraft:light_gray_wool\n" +
                "minecraft:polished_blackstone_pressure_plate\n" +
                "minecraft:jack_o_lantern\n" +
                "minecraft:prismarine_brick_stairs\n" +
                "minecraft:lime_stained_glass_pane\n" +
                "minecraft:spruce_fence\n" +
                "minecraft:vine\n" +
                "minecraft:quartz\n" +
                "minecraft:stone_stairs\n" +
                "minecraft:brain_coral_block\n" +
                "minecraft:lantern\n" +
                "minecraft:netherrack\n" +
                "minecraft:spruce_stairs\n" +
                "minecraft:light_gray_shulker_box\n" +
                "minecraft:black_concrete_powder\n" +
                "minecraft:red_shulker_box\n" +
                "minecraft:stone_pickaxe\n" +
                "minecraft:quartz_slab\n" +
                "minecraft:spruce_boat\n" +
                "minecraft:jungle_sapling\n" +
                "minecraft:lead\n" +
                "minecraft:light_gray_terracotta\n" +
                "minecraft:enchanting_table\n" +
                "minecraft:light_blue_wool\n" +
                "minecraft:yellow_stained_glass_pane\n" +
                "minecraft:leather_helmet\n" +
                "minecraft:dark_oak_button\n" +
                "minecraft:red_carpet\n" +
                "minecraft:enchanted_book\n" +
                "minecraft:orange_dye\n" +
                "minecraft:oak_fence_gate\n" +
                "minecraft:red_stained_glass\n" +
                "minecraft:soul_lantern\n" +
                "minecraft:warped_sign\n" +
                "minecraft:fermented_spider_eye\n" +
                "minecraft:birch_trapdoor\n" +
                "minecraft:black_stained_glass_pane\n" +
                "minecraft:writable_book\n" +
                "minecraft:iron_shovel\n" +
                "minecraft:armor_stand\n" +
                "minecraft:prismarine_wall\n" +
                "minecraft:note_block\n" +
                "minecraft:pink_terracotta\n" +
                "minecraft:grindstone\n" +
                "minecraft:cobblestone_slab\n" +
                "minecraft:barrel\n" +
                "minecraft:quartz_bricks\n" +
                "minecraft:cooked_chicken\n" +
                "minecraft:stone\n" +
                "minecraft:pink_carpet\n" +
                "minecraft:quartz_pillar\n" +
                "minecraft:warped_planks\n" +
                "minecraft:brown_carpet\n" +
                "minecraft:polished_blackstone_button\n" +
                "minecraft:stone_brick_slab\n" +
                "minecraft:brown_stained_glass\n" +
                "minecraft:nether_brick_wall\n" +
                "minecraft:orange_stained_glass_pane\n" +
                "minecraft:bow\n" +
                "minecraft:comparator\n" +
                "minecraft:chest\n" +
                "minecraft:yellow_terracotta\n" +
                "minecraft:rail\n" +
                "minecraft:blue_concrete_powder\n" +
                "minecraft:bricks\n" +
                "minecraft:birch_button\n" +
                "minecraft:red_nether_brick_slab\n" +
                "minecraft:ender_eye\n" +
                "minecraft:stone_bricks\n" +
                "minecraft:oak_fence\n" +
                "minecraft:golden_boots\n" +
                "minecraft:sea_lantern\n" +
                "minecraft:magma_block\n" +
                "minecraft:white_banner\n" +
                "minecraft:dropper\n" +
                "minecraft:arrow\n" +
                "minecraft:cauldron\n" +
                "minecraft:lime_terracotta\n" +
                "minecraft:iron_helmet\n" +
                "minecraft:brown_dye\n" +
                "minecraft:birch_pressure_plate\n" +
                "minecraft:red_wool\n" +
                "minecraft:chiseled_polished_blackstone\n" +
                "minecraft:white_stained_glass_pane\n" +
                "minecraft:yellow_stained_glass\n" +
                "minecraft:warped_door\n" +
                "minecraft:creeper_banner_pattern\n" +
                "minecraft:prismarine_brick_slab\n" +
                "minecraft:dispenser\n" +
                "minecraft:apple\n" +
                "minecraft:tnt\n" +
                "minecraft:spruce_trapdoor\n" +
                "minecraft:yellow_dye\n" +
                "minecraft:pink_wool\n" +
                "minecraft:purple_dye\n" +
                "minecraft:warped_fence_gate\n" +
                "minecraft:netherite_block\n" +
                "minecraft:gray_terracotta\n" +
                "minecraft:stick\n" +
                "minecraft:iron_ingot\n" +
                "minecraft:light_blue_stained_glass\n" +
                "minecraft:black_bed\n" +
                "minecraft:red_nether_brick_wall\n" +
                "minecraft:dark_oak_fence_gate\n" +
                "minecraft:sweet_berries\n" +
                "minecraft:blue_terracotta\n" +
                "minecraft:oak_door\n" +
                "minecraft:nether_brick_slab\n" +
                "minecraft:mycelium\n" +
                "minecraft:stone_brick_wall\n" +
                "minecraft:fishing_rod\n" +
                "minecraft:tripwire_hook\n" +
                "minecraft:beehive\n" +
                "minecraft:netherite_sword\n" +
                "minecraft:leather_boots\n" +
                "minecraft:golden_chestplate\n" +
                "minecraft:spruce_button\n" +
                "minecraft:mossy_stone_bricks\n" +
                "minecraft:furnace\n" +
                "minecraft:blast_furnace\n" +
                "minecraft:piston\n" +
                "minecraft:nether_quartz_ore\n" +
                "minecraft:magenta_stained_glass_pane\n" +
                "minecraft:smooth_quartz_stairs\n" +
                "minecraft:oak_trapdoor\n" +
                "minecraft:flint_and_steel\n" +
                "minecraft:scaffolding\n" +
                "minecraft:white_concrete_powder\n" +
                "minecraft:oak_sapling\n" +
                "minecraft:orange_terracotta\n" +
                "minecraft:cobblestone_wall\n" +
                "minecraft:smooth_quartz_slab\n" +
                "minecraft:honey_block\n" +
                "minecraft:birch_sign\n" +
                "minecraft:glistering_melon_slice\n" +
                "minecraft:magma_cream\n" +
                "minecraft:purple_terracotta\n" +
                "minecraft:light_blue_stained_glass_pane\n" +
                "minecraft:iron_trapdoor\n" +
                "minecraft:polished_blackstone_wall\n" +
                "minecraft:purple_shulker_box\n" +
                "minecraft:diorite_wall\n" +
                "minecraft:iron_sword\n" +
                "minecraft:jungle_planks\n" +
                "minecraft:white_dye\n" +
                "minecraft:brown_concrete_powder\n" +
                "minecraft:blue_wool\n" +
                "minecraft:stonecutter\n" +
                "minecraft:anvil\n" +
                "minecraft:andesite\n" +
                "minecraft:torch\n" +
                "minecraft:diorite_slab\n" +
                "minecraft:orange_bed\n" +
                "minecraft:diamond_chestplate\n" +
                "minecraft:ender_chest\n" +
                "minecraft:light_gray_concrete_powder\n" +
                "minecraft:smooth_stone\n" +
                "minecraft:jungle_fence_gate\n" +
                "minecraft:cut_sandstone\n" +
                "minecraft:orange_stained_glass\n" +
                "minecraft:pink_bed\n" +
                "minecraft:oak_pressure_plate\n" +
                "minecraft:dark_oak_wood\n" +
                "minecraft:birch_slab\n" +
                "minecraft:horn_coral_block\n" +
                "minecraft:slime_block\n" +
                "minecraft:loom\n" +
                "minecraft:polished_blackstone_slab\n" +
                "minecraft:lever\n" +
                "minecraft:bookshelf\n" +
                "minecraft:iron_bars\n" +
                "minecraft:red_concrete_powder\n" +
                "minecraft:quartz_block\n" +
                "minecraft:glass\n" +
                "minecraft:light_blue_terracotta\n" +
                "minecraft:repeater\n" +
                "minecraft:diamond_leggings\n" +
                "minecraft:cyan_stained_glass_pane\n" +
                "minecraft:melon_seeds\n" +
                "minecraft:birch_fence_gate\n" +
                "minecraft:polished_blackstone\n" +
                "minecraft:chiseled_quartz_block\n" +
                "minecraft:magenta_dye\n" +
                "minecraft:flower_pot\n" +
                "minecraft:glass_bottle\n" +
                "minecraft:target\n" +
                "minecraft:wooden_shovel\n" +
                "minecraft:emerald\n" +
                "minecraft:diamond_axe\n" +
                "minecraft:gravel\n" +
                "minecraft:prismarine_bricks\n" +
                "minecraft:spruce_door\n" +
                "minecraft:red_mushroom\n" +
                "minecraft:oak_wood\n" +
                "minecraft:hay_block\n" +
                "minecraft:campfire\n" +
                "minecraft:fire_coral_block\n" +
                "minecraft:blaze_rod\n" +
                "minecraft:dark_oak_sapling\n" +
                "minecraft:green_terracotta\n" +
                "minecraft:compass\n" +
                "minecraft:warped_nylium\n" +
                "minecraft:iron_block\n" +
                "minecraft:white_terracotta\n" +
                "minecraft:gold_ingot\n" +
                "minecraft:light_gray_dye\n" +
                "minecraft:spruce_fence_gate\n" +
                "minecraft:birch_stairs\n" +
                "minecraft:packed_ice\n" +
                "minecraft:yellow_concrete_powder\n" +
                "minecraft:prismarine\n" +
                "minecraft:stone_shovel\n" +
                "minecraft:smooth_stone_slab\n" +
                "minecraft:leather_leggings\n" +
                "minecraft:crimson_fence_gate\n" +
                "minecraft:yellow_bed\n" +
                "minecraft:red_terracotta\n" +
                "minecraft:bone_meal\n" +
                "minecraft:cyan_stained_glass\n" +
                "minecraft:pink_dye\n" +
                "minecraft:white_carpet\n" +
                "minecraft:orange_wool\n" +
                "minecraft:warped_trapdoor\n" +
                "minecraft:dark_oak_fence\n" +
                "minecraft:detector_rail\n" +
                "minecraft:ladder\n" +
                "minecraft:spruce_slab\n" +
                "minecraft:diamond_boots\n" +
                "minecraft:spruce_sapling\n" +
                "minecraft:redstone_block\n" +
                "minecraft:jungle_fence\n" +
                "minecraft:dark_oak_planks\n" +
                "minecraft:golden_helmet\n" +
                "minecraft:wheat\n" +
                "minecraft:coal_block\n" +
                "minecraft:firework_star\n" +
                "minecraft:purple_stained_glass_pane\n" +
                "minecraft:crossbow\n" +
                "minecraft:crimson_nylium\n" +
                "minecraft:polished_blackstone_brick_slab\n" +
                "minecraft:gray_concrete_powder\n" +
                "minecraft:polished_granite\n" +
                "minecraft:sandstone_slab\n" +
                "minecraft:conduit\n" +
                "minecraft:glowstone\n" +
                "minecraft:white_stained_glass\n" +
                "minecraft:green_stained_glass_pane\n" +
                "minecraft:jungle_slab\n" +
                "minecraft:beetroot_seeds\n" +
                "minecraft:polished_blackstone_brick_wall\n" +
                "minecraft:golden_apple\n" +
                "minecraft:oak_stairs\n" +
                "minecraft:wooden_axe\n" +
                "minecraft:crimson_fence\n" +
                "minecraft:warped_pressure_plate\n" +
                "minecraft:iron_leggings\n" +
                "minecraft:white_bed\n" +
                "minecraft:lime_wool\n" +
                "minecraft:nether_brick_stairs\n" +
                "minecraft:brick\n" +
                "minecraft:oak_planks\n" +
                "minecraft:dark_oak_boat\n" +
                "minecraft:pink_shulker_box\n" +
                "minecraft:sand\n" +
                "minecraft:cobblestone_stairs\n" +
                "minecraft:spruce_pressure_plate\n" +
                "minecraft:dark_oak_door\n" +
                "minecraft:hopper\n" +
                "minecraft:iron_boots\n" +
                "minecraft:cyan_terracotta\n" +
                "minecraft:chiseled_stone_bricks\n" +
                "minecraft:stone_hoe\n" +
                "minecraft:golden_sword\n" +
                "minecraft:honeycomb_block\n" +
                "minecraft:smoker\n" +
                "minecraft:quartz_stairs\n" +
                "minecraft:oak_slab\n" +
                "minecraft:item_frame\n" +
                "minecraft:crafting_table\n" +
                "minecraft:spruce_planks\n" +
                "minecraft:gold_ore\n" +
                "minecraft:brown_stained_glass_pane\n" +
                "minecraft:wooden_pickaxe\n" +
                "minecraft:baked_potato\n" +
                "minecraft:gold_block\n" +
                "minecraft:hopper_minecart\n" +
                "minecraft:brewing_stand\n" +
                "minecraft:birch_planks\n" +
                "minecraft:pumpkin_seeds\n" +
                "minecraft:sea_pickle\n" +
                "minecraft:diorite\n" +
                "minecraft:birch_sapling\n" +
                "minecraft:dark_oak_slab\n" +
                "minecraft:book\n" +
                "minecraft:iron_chestplate\n" +
                "minecraft:paper\n" +
                "minecraft:charcoal\n" +
                "minecraft:diamond_pickaxe\n" +
                "minecraft:emerald_block\n" +
                "minecraft:birch_fence\n" +
                "minecraft:warped_slab\n" +
                "minecraft:light_blue_dye\n" +
                "minecraft:leather_chestplate\n" +
                "minecraft:stone_sword\n" +
                "minecraft:snow_block\n" +
                "minecraft:polished_blackstone_brick_stairs\n" +
                "minecraft:redstone_torch\n" +
                "minecraft:light_gray_carpet\n" +
                "minecraft:light_gray_stained_glass_pane\n" +
                "minecraft:shears\n" +
                "minecraft:green_carpet\n" +
                "minecraft:sandstone_stairs\n" +
                "minecraft:nether_wart\n" +
                "minecraft:coarse_dirt\n" +
                "minecraft:wooden_sword\n" +
                "minecraft:purple_wool\n" +
                "minecraft:redstone\n" +
                "minecraft:coal\n" +
                "minecraft:light_gray_stained_glass\n" +
                "minecraft:stone_button\n" +
                "minecraft:dark_oak_trapdoor\n" +
                "minecraft:jungle_trapdoor\n" +
                "minecraft:gray_dye\n" +
                "minecraft:dark_oak_sign\n" +
                "minecraft:diamond_block\n" +
                "minecraft:glass_pane\n" +
                "minecraft:chorus_flower\n" +
                "minecraft:blue_ice\n" +
                "minecraft:yellow_shulker_box\n" +
                "minecraft:black_terracotta\n" +
                "minecraft:green_concrete_powder\n" +
                "minecraft:iron_axe\n" +
                "minecraft:spruce_wood\n" +
                "minecraft:slime_ball\n" +
                "minecraft:orange_concrete_powder\n" +
                "minecraft:lime_dye\n" +
                "minecraft:warped_button\n" +
                "minecraft:filled_map\n" +
                "minecraft:clay_ball\n" +
                "minecraft:chiseled_sandstone\n" +
                "minecraft:observer\n" +
                "minecraft:minecart\n" +
                "minecraft:sugar\n" +
                "minecraft:red_dye\n" +
                "minecraft:cyan_concrete_powder\n" +
                "minecraft:bone_block\n" +
                "minecraft:crimson_planks\n" +
                "minecraft:diamond_sword\n" +
                "minecraft:cyan_dye\n" +
                "minecraft:spruce_sign\n" +
                "minecraft:dark_oak_stairs\n" +
                "minecraft:pink_concrete_powder\n" +
                "minecraft:powered_rail\n" +
                "minecraft:activator_rail\n" +
                "minecraft:nether_bricks\n" +
                "minecraft:bucket\n" +
                "minecraft:stone_axe\n" +
                "minecraft:brown_terracotta\n" +
                "minecraft:air\n" +
                "minecraft:black_stained_glass\n" +
                "minecraft:blue_dye\n" +
                "minecraft:oak_boat\n" +
                "minecraft:magenta_terracotta\n" +
                "minecraft:white_wool\n" +
                "minecraft:gold_nugget\n" +
                "minecraft:brown_wool\n" +
                "minecraft:pink_stained_glass_pane\n" +
                "minecraft:dark_prismarine_slab\n" +
                "minecraft:green_wool\n" +
                "minecraft:nether_wart_block\n" +
                "minecraft:acacia_sapling\n" +
                "minecraft:acacia_planks\n" +
                "minecraft:end_crystal\n" +
                "minecraft:purple_concrete_powder\n" +
                "minecraft:blackstone_slab\n" +
                "minecraft:lapis_lazuli\n" +
                "minecraft:clay\n" +
                "minecraft:firework_rocket";
        String str2="minecraft:yellow_wool\n" +
                "minecraft:iron_leggings\n" +
                "minecraft:name_tag\n" +
                "minecraft:compass\n" +
                "minecraft:warped_slab\n" +
                "minecraft:brown_concrete_powder\n" +
                "minecraft:red_sand\n" +
                "minecraft:stone_shovel\n" +
                "minecraft:jungle_slab\n" +
                "minecraft:stone_bricks\n" +
                "minecraft:enchanting_table\n" +
                "minecraft:apple\n" +
                "minecraft:observer\n" +
                "minecraft:lantern\n" +
                "minecraft:polished_blackstone_brick_stairs\n" +
                "minecraft:blue_dye\n" +
                "minecraft:pink_wool\n" +
                "minecraft:cobblestone_stairs\n" +
                "minecraft:light_gray_shulker_box\n" +
                "minecraft:stone\n" +
                "minecraft:redstone_ore\n" +
                "minecraft:green_banner\n" +
                "minecraft:jungle_sapling\n" +
                "minecraft:orange_stained_glass_pane\n" +
                "minecraft:melon_seeds\n" +
                "minecraft:cooked_chicken\n" +
                "minecraft:fire_coral_block\n" +
                "minecraft:blue_ice\n" +
                "minecraft:light_blue_stained_glass\n" +
                "minecraft:leather_leggings\n" +
                "minecraft:iron_sword\n" +
                "minecraft:filled_map\n" +
                "minecraft:jungle_fence_gate\n" +
                "minecraft:loom\n" +
                "minecraft:oak_slab\n" +
                "minecraft:golden_carrot\n" +
                "minecraft:firework_star\n" +
                "minecraft:dark_prismarine\n" +
                "minecraft:spruce_slab\n" +
                "minecraft:quartz\n" +
                "minecraft:white_terracotta\n" +
                "minecraft:sweet_berries\n" +
                "minecraft:green_carpet\n" +
                "minecraft:sea_lantern\n" +
                "minecraft:pumpkin_seeds\n" +
                "minecraft:white_wool\n" +
                "minecraft:white_dye\n" +
                "minecraft:blue_stained_glass_pane\n" +
                "minecraft:polished_blackstone_slab\n" +
                "minecraft:golden_apple\n" +
                "minecraft:end_rod\n" +
                "minecraft:chiseled_quartz_block\n" +
                "minecraft:diorite_wall\n" +
                "minecraft:magenta_wool\n" +
                "minecraft:prismarine_bricks\n" +
                "minecraft:crafting_table\n" +
                "minecraft:lever\n" +
                "minecraft:warped_pressure_plate\n" +
                "minecraft:cyan_dye\n" +
                "minecraft:mossy_stone_bricks\n" +
                "minecraft:blaze_powder\n" +
                "minecraft:tnt\n" +
                "minecraft:golden_boots\n" +
                "minecraft:magenta_dye\n" +
                "minecraft:gray_terracotta\n" +
                "minecraft:white_carpet\n" +
                "minecraft:sandstone_slab\n" +
                "minecraft:birch_trapdoor\n" +
                "minecraft:jungle_fence\n" +
                "minecraft:smooth_stone_slab\n" +
                "minecraft:arrow\n" +
                "minecraft:chest_minecart\n" +
                "minecraft:warped_nylium\n" +
                "minecraft:red_carpet\n" +
                "minecraft:dark_oak_slab\n" +
                "minecraft:wooden_hoe\n" +
                "minecraft:light_blue_dye\n" +
                "minecraft:prismarine_brick_slab\n" +
                "minecraft:warped_fungus\n" +
                "minecraft:oak_sapling\n" +
                "minecraft:iron_axe\n" +
                "minecraft:barrel\n" +
                "minecraft:jungle_trapdoor\n" +
                "minecraft:bookshelf\n" +
                "minecraft:blue_stained_glass\n" +
                "minecraft:stone_sword\n" +
                "minecraft:magma_block\n" +
                "minecraft:cobblestone_slab\n" +
                "minecraft:polished_blackstone_button\n" +
                "minecraft:red_nether_bricks\n" +
                "minecraft:magma_cream\n" +
                "minecraft:lime_dye\n" +
                "minecraft:coal\n" +
                "minecraft:red_dye\n" +
                "minecraft:crimson_fungus\n" +
                "minecraft:leather_chestplate\n" +
                "minecraft:sea_pickle\n" +
                "minecraft:green_concrete_powder\n" +
                "minecraft:brown_stained_glass\n" +
                "minecraft:glass\n" +
                "minecraft:armor_stand\n" +
                "minecraft:pink_concrete_powder\n" +
                "minecraft:oak_planks\n" +
                "minecraft:orange_wool\n" +
                "minecraft:cut_sandstone\n" +
                "minecraft:golden_leggings\n" +
                "minecraft:polished_blackstone_pressure_plate\n" +
                "minecraft:green_stained_glass_pane\n" +
                "minecraft:black_terracotta\n" +
                "minecraft:polished_blackstone_brick_wall\n" +
                "minecraft:stick\n" +
                "minecraft:yellow_terracotta\n" +
                "minecraft:piston\n" +
                "minecraft:tube_coral_block\n" +
                "minecraft:orange_dye\n" +
                "minecraft:spruce_trapdoor\n" +
                "minecraft:yellow_bed\n" +
                "minecraft:netherrack\n" +
                "minecraft:nether_brick_slab\n" +
                "minecraft:redstone_torch\n" +
                "minecraft:diamond_hoe\n" +
                "minecraft:yellow_shulker_box\n" +
                "minecraft:gray_stained_glass_pane\n" +
                "minecraft:black_dye\n" +
                "minecraft:soul_torch\n" +
                "minecraft:blue_concrete_powder\n" +
                "minecraft:mossy_cobblestone\n" +
                "minecraft:furnace\n" +
                "minecraft:smithing_table\n" +
                "minecraft:iron_trapdoor\n" +
                "minecraft:bone_meal\n" +
                "minecraft:grindstone\n" +
                "minecraft:lime_wool\n" +
                "minecraft:white_stained_glass_pane\n" +
                "minecraft:bricks\n" +
                "minecraft:brewing_stand\n" +
                "minecraft:spruce_fence\n" +
                "minecraft:dark_oak_door\n" +
                "minecraft:spruce_sapling\n" +
                "minecraft:pink_stained_glass_pane\n" +
                "minecraft:ladder\n" +
                "minecraft:nautilus_shell\n" +
                "minecraft:jungle_planks\n" +
                "minecraft:chain\n" +
                "minecraft:item_frame\n" +
                "minecraft:slime_block\n" +
                "minecraft:rail\n" +
                "minecraft:minecart\n" +
                "minecraft:clay_ball\n" +
                "minecraft:sugar\n" +
                "minecraft:prismarine\n" +
                "minecraft:iron_block\n" +
                "minecraft:purple_shulker_box\n" +
                "minecraft:spruce_boat\n" +
                "minecraft:paper\n" +
                "minecraft:gravel\n" +
                "minecraft:light_gray_stained_glass_pane\n" +
                "minecraft:light_gray_concrete_powder\n" +
                "minecraft:vine\n" +
                "minecraft:orange_terracotta\n" +
                "minecraft:pink_stained_glass\n" +
                "minecraft:dark_oak_sapling\n" +
                "minecraft:conduit\n" +
                "minecraft:black_wool\n" +
                "minecraft:wooden_shovel\n" +
                "minecraft:light_gray_carpet\n" +
                "minecraft:hopper_minecart\n" +
                "minecraft:dropper\n" +
                "minecraft:pink_bed\n" +
                "minecraft:coarse_dirt\n" +
                "minecraft:chest\n" +
                "minecraft:red_nether_brick_slab\n" +
                "minecraft:cauldron\n" +
                "minecraft:painting\n" +
                "minecraft:chiseled_sandstone\n" +
                "minecraft:dark_oak_fence_gate\n" +
                "minecraft:polished_granite\n" +
                "minecraft:dark_oak_stairs\n" +
                "minecraft:glistering_melon_slice\n" +
                "minecraft:dispenser\n" +
                "minecraft:brown_dye\n" +
                "minecraft:polished_blackstone\n" +
                "minecraft:lime_stained_glass_pane\n" +
                "minecraft:acacia_sapling\n" +
                "minecraft:green_terracotta\n" +
                "minecraft:magenta_concrete_powder\n" +
                "minecraft:red_banner\n" +
                "minecraft:iron_ingot\n" +
                "minecraft:netherite_block\n" +
                "minecraft:warped_fence_gate\n" +
                "minecraft:warped_sign\n" +
                "minecraft:flower_pot\n" +
                "minecraft:quartz_slab\n" +
                "minecraft:warped_stairs\n" +
                "minecraft:leather_boots\n" +
                "minecraft:white_banner\n" +
                "minecraft:blaze_rod\n" +
                "minecraft:diamond_chestplate\n" +
                "minecraft:smooth_quartz_stairs\n" +
                "minecraft:warped_trapdoor\n" +
                "minecraft:redstone_block\n" +
                "minecraft:sandstone\n" +
                "minecraft:yellow_stained_glass\n" +
                "minecraft:oak_door\n" +
                "minecraft:scaffolding\n" +
                "minecraft:red_stained_glass_pane\n" +
                "minecraft:lime_concrete_powder\n" +
                "minecraft:birch_pressure_plate\n" +
                "minecraft:golden_sword\n" +
                "minecraft:spruce_sign\n" +
                "minecraft:crimson_fence_gate\n" +
                "minecraft:stone_brick_wall\n" +
                "minecraft:fermented_spider_eye\n" +
                "minecraft:diamond_helmet\n" +
                "minecraft:stone_pickaxe\n" +
                "minecraft:red_shulker_box\n" +
                "minecraft:cyan_stained_glass_pane\n" +
                "minecraft:red_mushroom\n" +
                "minecraft:spruce_planks\n" +
                "minecraft:gray_stained_glass\n" +
                "minecraft:enchanted_book\n" +
                "minecraft:repeater\n" +
                "minecraft:andesite\n" +
                "minecraft:magenta_terracotta\n" +
                "minecraft:birch_planks\n" +
                "minecraft:iron_pickaxe\n" +
                "minecraft:bubble_coral_block\n" +
                "minecraft:horn_coral_block\n" +
                "minecraft:gold_ingot\n" +
                "minecraft:brown_terracotta\n" +
                "minecraft:diamond_leggings\n" +
                "minecraft:golden_chestplate\n" +
                "minecraft:spruce_pressure_plate\n" +
                "minecraft:polished_blackstone_wall\n" +
                "minecraft:redstone\n" +
                "minecraft:smooth_stone\n" +
                "minecraft:stone_pressure_plate\n" +
                "minecraft:quartz_bricks\n" +
                "minecraft:end_crystal\n" +
                "minecraft:shears\n" +
                "minecraft:dark_oak_wood\n" +
                "minecraft:prismarine_brick_stairs\n" +
                "minecraft:comparator\n" +
                "minecraft:ender_eye\n" +
                "minecraft:oak_stairs\n" +
                "minecraft:cyan_concrete_powder\n" +
                "minecraft:gray_dye\n" +
                "minecraft:white_stained_glass\n" +
                "minecraft:orange_stained_glass\n" +
                "minecraft:cocoa_beans\n" +
                "minecraft:stonecutter\n" +
                "minecraft:iron_nugget\n" +
                "minecraft:polished_blackstone_bricks\n" +
                "minecraft:light_gray_wool\n" +
                "minecraft:birch_fence\n" +
                "minecraft:light_gray_terracotta\n" +
                "minecraft:granite\n" +
                "minecraft:green_stained_glass\n" +
                "minecraft:diamond_pickaxe\n" +
                "minecraft:cobblestone_wall\n" +
                "minecraft:orange_concrete_powder\n" +
                "minecraft:sand\n" +
                "minecraft:warped_button\n" +
                "minecraft:chiseled_polished_blackstone\n" +
                "minecraft:warped_planks\n" +
                "minecraft:nether_brick_stairs\n" +
                "minecraft:cyan_wool\n" +
                "minecraft:hay_block\n" +
                "minecraft:fletching_table\n" +
                "minecraft:smooth_quartz_slab\n" +
                "minecraft:netherite_ingot\n" +
                "minecraft:wheat\n" +
                "minecraft:dark_oak_fence\n" +
                "minecraft:lime_stained_glass\n" +
                "minecraft:composter\n" +
                "minecraft:jukebox\n" +
                "minecraft:cyan_terracotta\n" +
                "minecraft:chorus_flower\n" +
                "minecraft:pink_terracotta\n" +
                "minecraft:snow_block\n" +
                "minecraft:birch_sign\n" +
                "minecraft:crimson_fence\n" +
                "minecraft:wooden_pickaxe\n" +
                "minecraft:red_wool\n" +
                "minecraft:crimson_planks\n" +
                "minecraft:birch_fence_gate\n" +
                "minecraft:lectern\n" +
                "minecraft:dark_prismarine_slab\n" +
                "minecraft:dark_oak_button\n" +
                "minecraft:campfire\n" +
                "minecraft:iron_boots\n" +
                "minecraft:nether_quartz_ore\n" +
                "minecraft:lime_terracotta\n" +
                "minecraft:magenta_stained_glass_pane\n" +
                "minecraft:light_gray_stained_glass\n" +
                "minecraft:white_bed\n" +
                "minecraft:red_concrete_powder\n" +
                "minecraft:brown_wool\n" +
                "minecraft:yellow_concrete_powder\n" +
                "minecraft:white_concrete_powder\n" +
                "minecraft:quartz_pillar\n" +
                "minecraft:orange_shulker_box\n" +
                "minecraft:target\n" +
                "minecraft:red_stained_glass\n" +
                "minecraft:glass_bottle\n" +
                "minecraft:spruce_wood\n" +
                "minecraft:purple_wool\n" +
                "minecraft:soul_lantern\n" +
                "minecraft:honey_block\n" +
                "minecraft:diorite\n" +
                "minecraft:diamond_shovel\n" +
                "minecraft:leather_helmet\n" +
                "minecraft:gray_wool\n" +
                "minecraft:iron_door\n" +
                "minecraft:nether_bricks\n" +
                "minecraft:purple_dye\n" +
                "minecraft:oak_wood\n" +
                "minecraft:blue_terracotta\n" +
                "minecraft:gold_nugget\n" +
                "minecraft:stone_button\n" +
                "minecraft:diorite_slab\n" +
                "minecraft:diamond_sword\n" +
                "minecraft:ender_chest\n" +
                "minecraft:dark_oak_trapdoor\n" +
                "minecraft:diamond_axe\n" +
                "minecraft:iron_helmet\n" +
                "minecraft:black_stained_glass_pane\n" +
                "minecraft:gold_block\n" +
                "minecraft:stone_axe\n" +
                "minecraft:orange_bed\n" +
                "minecraft:detector_rail\n" +
                "minecraft:nether_brick_wall\n" +
                "minecraft:jack_o_lantern\n" +
                "minecraft:lead\n" +
                "minecraft:firework_rocket\n" +
                "minecraft:purple_stained_glass_pane\n" +
                "minecraft:pink_shulker_box\n" +
                "minecraft:iron_chestplate\n" +
                "minecraft:acacia_planks\n" +
                "minecraft:bone_block\n" +
                "minecraft:black_stained_glass\n" +
                "minecraft:brain_coral_block\n" +
                "minecraft:sandstone_stairs\n" +
                "minecraft:yellow_stained_glass_pane\n" +
                "minecraft:smoker\n" +
                "minecraft:purple_terracotta\n" +
                "minecraft:nether_brick_fence\n" +
                "minecraft:hopper\n" +
                "minecraft:emerald\n" +
                "minecraft:bow\n" +
                "minecraft:note_block\n" +
                "minecraft:black_bed\n" +
                "minecraft:redstone_lamp\n" +
                "minecraft:quartz_stairs\n" +
                "minecraft:dark_oak_sign\n" +
                "minecraft:oak_boat\n" +
                "minecraft:slime_ball\n" +
                "minecraft:stone_brick_slab\n" +
                "minecraft:flint_and_steel\n" +
                "minecraft:brown_carpet\n" +
                "minecraft:stone_stairs\n" +
                "minecraft:yellow_dye\n" +
                "minecraft:sticky_piston\n" +
                "minecraft:cyan_stained_glass\n" +
                "minecraft:glass_pane\n" +
                "minecraft:iron_shovel\n" +
                "minecraft:fishing_rod\n" +
                "minecraft:crimson_nylium\n" +
                "minecraft:oak_trapdoor\n" +
                "minecraft:spruce_fence_gate\n" +
                "minecraft:birch_sapling\n" +
                "minecraft:diamond_block\n" +
                "minecraft:pink_dye\n" +
                "minecraft:stone_slab\n" +
                "minecraft:blackstone_slab\n" +
                "minecraft:brick\n" +
                "minecraft:wooden_axe\n" +
                "minecraft:spruce_stairs\n" +
                "minecraft:activator_rail\n" +
                "minecraft:nether_wart\n" +
                "minecraft:nether_brick\n" +
                "minecraft:oak_pressure_plate\n" +
                "minecraft:light_blue_concrete_powder\n" +
                "minecraft:glowstone\n" +
                "minecraft:nether_wart_block\n" +
                "minecraft:turtle_helmet\n" +
                "minecraft:dark_oak_boat\n" +
                "minecraft:wooden_sword\n" +
                "minecraft:crossbow\n" +
                "minecraft:green_wool\n" +
                "minecraft:light_blue_stained_glass_pane\n" +
                "minecraft:oak_fence_gate\n" +
                "minecraft:tripwire_hook\n" +
                "minecraft:black_concrete_powder\n" +
                "minecraft:spruce_button\n" +
                "minecraft:birch_button\n" +
                "minecraft:prismarine_wall\n" +
                "minecraft:book\n" +
                "minecraft:stone_brick_stairs\n" +
                "minecraft:gold_ore\n" +
                "minecraft:light_blue_wool\n" +
                "minecraft:warped_door\n" +
                "minecraft:birch_stairs\n" +
                "minecraft:baked_potato\n" +
                "minecraft:polished_blackstone_brick_slab\n" +
                "minecraft:quartz_block\n" +
                "minecraft:lapis_lazuli\n" +
                "minecraft:coal_ore\n" +
                "minecraft:creeper_banner_pattern\n" +
                "minecraft:stone_hoe\n" +
                "minecraft:bucket\n" +
                "minecraft:torch\n" +
                "minecraft:blue_wool\n" +
                "minecraft:diamond_boots\n" +
                "minecraft:spruce_door\n" +
                "minecraft:powered_rail\n" +
                "minecraft:coal_block\n" +
                "minecraft:writable_book\n" +
                "minecraft:golden_helmet\n" +
                "minecraft:honeycomb_block\n" +
                "minecraft:light_blue_terracotta\n" +
                "minecraft:packed_ice\n" +
                "minecraft:blast_furnace\n" +
                "minecraft:beehive\n" +
                "minecraft:red_terracotta\n" +
                "minecraft:emerald_block\n" +
                "minecraft:birch_slab\n" +
                "minecraft:pink_carpet\n" +
                "minecraft:iron_bars\n" +
                "minecraft:mycelium\n" +
                "minecraft:oak_sign\n" +
                "minecraft:anvil\n" +
                "minecraft:brown_stained_glass_pane\n" +
                "minecraft:red_nether_brick_wall\n" +
                "minecraft:purple_concrete_powder\n" +
                "minecraft:oak_fence\n" +
                "minecraft:dark_oak_planks\n" +
                "minecraft:light_gray_dye\n" +
                "minecraft:chiseled_stone_bricks\n" +
                "minecraft:charcoal\n" +
                "minecraft:clay\n" +
                "minecraft:beetroot_seeds\n" +
                "minecraft:soul_campfire\n" +
                "minecraft:gray_concrete_powder\n" +
                "minecraft:netherite_sword";
        String[] split1 = str1.split("\n");
        String[] split2 = str2.split("\n");
        List<String> strings1 = Arrays.asList(split1);
        List<String> strings2 = Arrays.asList(split2);
        for (String s : strings1) {
            if(!strings2.contains(s)){
                System.out.println(s);
            }
        }

        for (String s : strings2) {
            if(!strings1.contains(s)){
                System.out.println(s);
            }
        }
    }
}
